"""Generate an external critic brief from briefing.md + TikZ + rendered PNG."""

from __future__ import annotations

import sys
from pathlib import Path

from prompt_gen import parse_briefing, parse_spec

MISSING_INVARIANTS = (
    "(none provided — reviewer should infer plausible physics constraints from §1+§2)"
)


def _require_file(path: Path, hint: str | None = None) -> None:
    if path.exists():
        return
    message = f"missing {path}"
    if hint:
        message = f"{message}; {hint}"
    raise FileNotFoundError(message)


def _author_intent(sections: dict[int, tuple[str, str]]) -> str:
    topic = sections.get(1, ("", ""))[1].strip()
    composition = sections.get(3, ("", ""))[1].strip()
    parts = [part for part in [topic, composition] if part]
    return "\n\n".join(parts) if parts else "(briefing.md §1 and §3 are empty)"


def generate_for(example_dir: Path) -> str:
    """Compose the reviewer brief for one `examples/<name>` directory."""
    if not example_dir.is_dir():
        raise FileNotFoundError(f"not a directory: {example_dir}")

    spec_path = example_dir / "spec.yaml"
    briefing_path = example_dir / "briefing.md"
    _require_file(spec_path)
    _require_file(briefing_path)

    spec = parse_spec(spec_path.read_text(encoding="utf-8"))
    sections = parse_briefing(briefing_path.read_text(encoding="utf-8"))
    name = str(spec.get("name") or example_dir.name)

    tex_path = example_dir / f"{name}.tex"
    png_path = example_dir / "build" / f"{name}.png"
    _require_file(tex_path)
    _require_file(png_path, "run /fig_compile first")

    tex = tex_path.read_text(encoding="utf-8")
    if not tex.endswith("\n"):
        tex += "\n"
    invariants = sections.get(6, ("", ""))[1].strip() or MISSING_INVARIANTS
    render_path = png_path.resolve()

    return f"""# Reviewer brief — {name}

**Render to attach:** `{render_path}`
(Attach this PNG to your critic before sending the brief.)

## Author intent (from briefing.md)
{_author_intent(sections)}

## Physics invariants the figure MUST honor
{invariants}

## Source under review (TikZ)
```tex
{tex}```

## Review rubric

### A. Physics correctness
- For each invariant in the section above, verify the rendered figure preserves it.
  Cite the .tex line numbers where a violation is seen.
- Check band ordering, arrow directions, label↔target binding, and any quantitative claim
  that contradicts the briefing.

### B. Aesthetic placement
- Label positioning: is each label clearly attached to its intended target? Is the offset
  consistent across labels of the same kind?
- Whitespace: does the figure feel cluttered or balanced?
- Visual hierarchy: are the most important elements visually dominant?
- Palette: are colors used consistently with their semantic role
  (e.g., blue=conduction, red=valence, amber=trap)?
- Nature-schematic style: minimal, sans-serif, no unnecessary text?

## Output format requested
Produce a single Markdown table with columns:
| severity | category | .tex line(s) | finding | suggested fix |

Severity is one of: BLOCKER, MAJOR, MINOR, NIT.
Category is one of: physics, label_placement, whitespace, hierarchy, palette, style.

End with a 1-paragraph "Overall verdict" summarizing whether the figure is ready to
export or needs revision.

---
(Generated by figure-agent /fig_review for {name}. Brief is API-free. Paste this brief
plus the attached PNG into your critic of choice.)
"""


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: review_brief.py <example_dir>", file=sys.stderr)
        return 2

    try:
        brief = generate_for(Path(sys.argv[1]))
    except FileNotFoundError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    print(brief, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
